version: "2.1"

services:
  minio:
    image: minio/minio:RELEASE.2021-07-22T05-23-32Z
    command:
      - server
      - /data
      - --console-address
      - ":9001"
    ports:
      - 9000:9000
      - 80:9001
    volumes:
      - data:/data 

volumes:
  data:
